name: stories
description: World Stories Collection

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  async: ^2.11.0
  cloud_firestore: ^4.9.0
  connectivity_plus: ^4.0.1
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.6.0
  http: ^1.1.0
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.0
  stacked: ^3.4.1
  tuple: ^2.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  image: "assets/icons/splash.png"
  android: true
  ios: true
flutter_launcher_icons:
  image_path: "assets/icons/iOS.png"
  android: false
  ios: true
  remove_alpha_ios: true


flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_intl:
  enable: true
