// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDQnTJ-aYoMxU5zlWaRcOo2D8gYFF0ao',
    appId: '1:225574218976:web:8579ada588cdada07bf485',
    messagingSenderId: '225574218976',
    projectId: 'world-stories-collection',
    authDomain: 'world-stories-collection.firebaseapp.com',
    storageBucket: 'world-stories-collection.appspot.com',
    measurementId: 'G-M8J5V8VHYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoK8u2r8t43ZdPSlFCJe0UL7Qcg0NrLEA',
    appId: '1:225574218976:android:79d030d1140d20967bf485',
    messagingSenderId: '225574218976',
    projectId: 'world-stories-collection',
    storageBucket: 'world-stories-collection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:225574218976:ios:52bb05233e133df07bf485',
    messagingSenderId: '225574218976',
    projectId: 'world-stories-collection',
    storageBucket: 'world-stories-collection.appspot.com',
    iosClientId: '225574218976-3a453pmigvd2ueh5gg183av2q04uahcs.apps.googleusercontent.com',
    iosBundleId: 'com.fishimve.stories',
  );
}
